# Generated by Django 3.2.4 on 2021-07-18 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_articles_orderitem_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller_if',
        ),
    ]
