# Generated by Django 3.2.5 on 2021-08-27 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_alter_imagearticle_article'),
        ('cart', '0010_auto_20210816_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitems', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderitems', to='cart.order'),
        ),
    ]
