version: '3'

services:
  ecommerce_django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_django
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - pgdb

  pgdb:
    image: postgres:9.6.22-alpine
    container_name: pgdb
    env_file: .env
    volumes:
      - ./ecommerce-postgres:/var/lib/postgresql/data
    ports:
      - 5431:5432
