# Generated by Django 3.2.4 on 2021-06-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210615_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
