# Generated by Django 3.2.4 on 2021-07-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20210618_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagearticle',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='imagearticle',
            name='article_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
