# Generated by Django 3.2.4 on 2021-07-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagearticle',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
