# Generated by Django 3.2.4 on 2021-07-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_imagearticle_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagearticle',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
