# Generated by Django 3.2.4 on 2021-07-15 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_alter_imagearticle_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
