# Generated by Django 3.2.4 on 2021-07-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20210715_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
