# Generated by Django 3.2.5 on 2021-07-30 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_alter_article_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.article'),
        ),
    ]
