# Generated by Django 3.2.5 on 2021-07-30 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_alter_imagearticle_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
    ]
