# Generated by Django 3.2.5 on 2021-08-16 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_alter_imagearticle_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagearticles', to='articles.article'),
        ),
    ]
