# Generated by Django 3.2.4 on 2021-06-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210618_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='seller',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='images/profiles/'),
        ),
    ]
