# Generated by Django 3.2.4 on 2021-07-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='address',
            name='town_city',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=150, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=150, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=50, null=True, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2'),
        ),
    ]
